language: node_js
node_js:
- '12'
install:
- yarn install
script:
- yarn test:coverage_report
- yarn build
- docker build -t $TRAVIS_REPO_SLUG .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $TRAVIS_REPO_SLUG
env:
  global:
    secure: T7kdOISLD24GBiDWxXuVc8S8eqB/CtJ67xz5ryLXCiCFL4JbcpeXC99uQfwyiwuOj5SMNBjVfK64jJlMnO2IHiDY+IY583nHEQchfOaDMfy9tGDsEM65Yv6nEXwTl08eEaDaF0L2pbvzWoW5XuJiHsQlJQztnC2mlKuIwwb0Xp1EHNdA/1QfP7/0tL6e+u9RFGePdmx646JB/jgmG0kTXQ5CL5cWFNZ9vG8Xq/Fy3WKO5jt92vkANhv42i+ATq1jaMOZt7+oWvQgHCJ75EPr8BhQgi3H4ECG/Hkeh4Rz3wMyT+Mq2w2yUUSrk3Le9hID/lQq3C0XGBvnG5qwks+HawEWp1i4ob0l08kJbF/VrXOylCmq1VxOIdx3nFgTuxX5crQ9kbT/vj5NPT6sTo5FfcodP9r0A8+Pv21eC84MlxR1yKXkWUkREnan4aqwbHEu+uJWlELJCQO/zYApuW45Y0fpc+Ws3KwNasaC076C8fzx3jy14HFOOkrlioA5K5vbhHT92PaNQeLkfgmydpytAHYHdVaOiWIWJlcjirCOljqiEF+S9bajHGel1EelvZoY5fXwoHPPYWmeP7jDyJGOvlteAj/dgNDi3Bo+eakEmRs0P4utoUL6pydJuNX/BaQN8DIUhlFF+kZirSRhdb2z4Txldxr56zQgOgpauP/nanI=
