language: node_js
node_js:
- '12'
install:
- yarn install
script:
- yarn build
- yarn test:coverage_report
deploy:
  provider: surge
  skip_cleanup: true
  project: "./build"
  domain: https://gh-probe.surge.sh
env:
  global:
    secure: ViZCzhAweDKoDILb4znaNvgNuEF9FlgDEnZknmIwg0lMEg64S1wwIymqo/5fntklgSajDNfbKCR7LQtqB1jP465Pa1LhjejPulv2ZSP38QfcvnDINTuGeZM9KRa0QLO2oNR2zHeGhlsMWCJE90S/4lsKYK7RZ8X89WnseeemDbmkc5t+4A+Ow6qlksxk9Cun6ZBt9Lxgwn/po2BnCEh+FjuI6dZnB5TIeaKO+gozc9dZXAR/nINh9yXzszaC5RXQieE4J5nQMxmofwoVrZG3ouyalb8tHjb4VTwo0w40qUHkSc/6hMuKEqJyUPPzWQMnXrU/2ch5UzDi0fceydCrUcT+Yij2UDTMyufTqbYowq+vMi5ANL/0CiVmz1Rc3A2BhBn2+QPQmuVjRGQcr5U3uSHW6uDJjkHJPiZoEzOh+UtI+eH0McyFtkXKqCt84taVBf/smkU3A4UkaqFqR45tepy8fFqQc7xRah3s/j2e5EiOAFkhXqa/rSd+vR9qu7MIhnE+nbXQ6wH2BNOfEVbr/3Xw8IV2nFe/B5xskuEh8JP0+ikDmFHONDIFlQUTWxTRpXkdcLFYfhkMslHar4iKLGwOOIA4uC+roLAuMFEduJmLLbxjwl3vif6lfIj3f9ZGBPngF9XoTJrGs/VsWME8AI14aOmwPVvP0xVD7hMcz7Q=
